name: "Kubeval"
description: "Validate Kubernetes manifests using the upstream Schemas"
author: "Gareth Rushgrove"
branding:
  icon: "check"
  color: "green"
inputs:
  directories:
    description: "A comma-separated list of directories to recursively search for YAML documents"
    default: "."
  ignore_missing_schemas:
    description: "Skip validation for resource definitions without a schema"
    default: true
  ignored_filename_patterns:
    description: "A comma-separated list of regular expressions specifying filenames to ignore"
  kubernetes_version:
    description: "Version of Kubernetes to validate against"
    default: "master"
  openshift:
    description: "Whether to use the schemas from OpenShift rather than Kubernetes"
    default: false
  output:
    description: "The format of the output of this script. Options are: [stdout json tap]"
    default: "stdout"
  strict:
    description: "Disallow additional properties not in schema"
    default: true
runs:
  using: 'docker'
  image: './Dockerfile'
  args:
  - --directories=${{ inputs.directories }}
  - --ignore-missing-schemas=${{ inputs.ignore_missing_schemas }}
  - --ignored-filename-patterns=${{ inputs.ignored_filename_patterns }}
  - --kubernetes-version=${{ inputs.kubernetes_version }}
  - --openshift=${{ inputs.openshift }}
  - --output=${{ inputs.output }}
  - --strict=${{ inputs.strict }}
